server.port=8082

spring.application.name=ailifeos

# H2 Database connection
spring.datasource.url=jdbc:h2:mem:ailifeosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA Config
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JWT Config
jwt.secret=458316279F8C62A8AE3AB042DCFE36B04B99D0F340DDB61173BF71CB2B3CF0FE
jwt.expirationMs=86400000
